name = "roufouf-web"
main = "apps/web/.vercel/output/static/_worker.js/index.js"
compatibility_date = "2026-04-30"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "apps/web/.vercel/output/static"
binding = "ASSETS"
